//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisiProject.FacturaDigitalWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.facturadigital.com.mx/soap/FacturaDigitalWebService", ConfigurationName="FacturaDigitalWS.FacturaDigitalWebServicePortType")]
    public interface FacturaDigitalWebServicePortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.facturadigital.com.mx/SecureWebService) of message generarCFDIPorTextoRequest does not match the default value (http://www.facturadigital.com.mx/soap/FacturaDigitalWebService)
        [System.ServiceModel.OperationContractAttribute(Action="https://www.facturadigital.com.mx/sistemacfdi32/webservices/TimbradoWS.php/genera" +
            "rCFDIPorTexto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        DisiProject.FacturaDigitalWS.generarCFDIPorTextoResponse generarCFDIPorTexto(DisiProject.FacturaDigitalWS.generarCFDIPorTextoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.facturadigital.com.mx/sistemacfdi32/webservices/TimbradoWS.php/genera" +
            "rCFDIPorTexto", ReplyAction="*")]
        System.Threading.Tasks.Task<DisiProject.FacturaDigitalWS.generarCFDIPorTextoResponse> generarCFDIPorTextoAsync(DisiProject.FacturaDigitalWS.generarCFDIPorTextoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.facturadigital.com.mx/SecureWebService) of message cancelarCFDIRequest does not match the default value (http://www.facturadigital.com.mx/soap/FacturaDigitalWebService)
        [System.ServiceModel.OperationContractAttribute(Action="https://www.facturadigital.com.mx/sistemacfdi32/webservices/TimbradoWS.php/cancel" +
            "arCFDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        DisiProject.FacturaDigitalWS.cancelarCFDIResponse cancelarCFDI(DisiProject.FacturaDigitalWS.cancelarCFDIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.facturadigital.com.mx/sistemacfdi32/webservices/TimbradoWS.php/cancel" +
            "arCFDI", ReplyAction="*")]
        System.Threading.Tasks.Task<DisiProject.FacturaDigitalWS.cancelarCFDIResponse> cancelarCFDIAsync(DisiProject.FacturaDigitalWS.cancelarCFDIRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.facturadigital.com.mx/SecureWebService) of message consultarCreditosRequest does not match the default value (http://www.facturadigital.com.mx/soap/FacturaDigitalWebService)
        [System.ServiceModel.OperationContractAttribute(Action="https://www.facturadigital.com.mx/sistemacfdi32/webservices/TimbradoWS.php/consul" +
            "tarCreditos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        DisiProject.FacturaDigitalWS.consultarCreditosResponse consultarCreditos(DisiProject.FacturaDigitalWS.consultarCreditosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.facturadigital.com.mx/sistemacfdi32/webservices/TimbradoWS.php/consul" +
            "tarCreditos", ReplyAction="*")]
        System.Threading.Tasks.Task<DisiProject.FacturaDigitalWS.consultarCreditosResponse> consultarCreditosAsync(DisiProject.FacturaDigitalWS.consultarCreditosRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (https://www.facturadigital.com.mx/SecureWebService) of message enviarCorreoRequest does not match the default value (http://www.facturadigital.com.mx/soap/FacturaDigitalWebService)
        [System.ServiceModel.OperationContractAttribute(Action="https://www.facturadigital.com.mx/sistemacfdi32/webservices/TimbradoWS.php/enviar" +
            "Correo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        DisiProject.FacturaDigitalWS.enviarCorreoResponse enviarCorreo(DisiProject.FacturaDigitalWS.enviarCorreoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.facturadigital.com.mx/sistemacfdi32/webservices/TimbradoWS.php/enviar" +
            "Correo", ReplyAction="*")]
        System.Threading.Tasks.Task<DisiProject.FacturaDigitalWS.enviarCorreoResponse> enviarCorreoAsync(DisiProject.FacturaDigitalWS.enviarCorreoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.facturadigital.com.mx/soap/FacturaDigitalWebService")]
    public partial class RespuestaGenerarCFDIPorTexto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensajeErrorField;
        
        private string versionCFDIField;
        
        private string noCertificadoField;
        
        private string certificadoField;
        
        private string selloCFDField;
        
        private string fechaTimbradoField;
        
        private string uUIDField;
        
        private string noCertificadoSATField;
        
        private string versionTFDField;
        
        private string selloSATField;
        
        private string cadenaOrigTFDField;
        
        private string cadenaQRField;
        
        private string tokenDownloadField;
        
        private string urlDownloadXMLField;
        
        private string urlDownloadPDFField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        public string mensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("mensajeError");
            }
        }
        
        /// <remarks/>
        public string versionCFDI {
            get {
                return this.versionCFDIField;
            }
            set {
                this.versionCFDIField = value;
                this.RaisePropertyChanged("versionCFDI");
            }
        }
        
        /// <remarks/>
        public string noCertificado {
            get {
                return this.noCertificadoField;
            }
            set {
                this.noCertificadoField = value;
                this.RaisePropertyChanged("noCertificado");
            }
        }
        
        /// <remarks/>
        public string certificado {
            get {
                return this.certificadoField;
            }
            set {
                this.certificadoField = value;
                this.RaisePropertyChanged("certificado");
            }
        }
        
        /// <remarks/>
        public string selloCFD {
            get {
                return this.selloCFDField;
            }
            set {
                this.selloCFDField = value;
                this.RaisePropertyChanged("selloCFD");
            }
        }
        
        /// <remarks/>
        public string FechaTimbrado {
            get {
                return this.fechaTimbradoField;
            }
            set {
                this.fechaTimbradoField = value;
                this.RaisePropertyChanged("FechaTimbrado");
            }
        }
        
        /// <remarks/>
        public string UUID {
            get {
                return this.uUIDField;
            }
            set {
                this.uUIDField = value;
                this.RaisePropertyChanged("UUID");
            }
        }
        
        /// <remarks/>
        public string noCertificadoSAT {
            get {
                return this.noCertificadoSATField;
            }
            set {
                this.noCertificadoSATField = value;
                this.RaisePropertyChanged("noCertificadoSAT");
            }
        }
        
        /// <remarks/>
        public string versionTFD {
            get {
                return this.versionTFDField;
            }
            set {
                this.versionTFDField = value;
                this.RaisePropertyChanged("versionTFD");
            }
        }
        
        /// <remarks/>
        public string selloSAT {
            get {
                return this.selloSATField;
            }
            set {
                this.selloSATField = value;
                this.RaisePropertyChanged("selloSAT");
            }
        }
        
        /// <remarks/>
        public string cadenaOrigTFD {
            get {
                return this.cadenaOrigTFDField;
            }
            set {
                this.cadenaOrigTFDField = value;
                this.RaisePropertyChanged("cadenaOrigTFD");
            }
        }
        
        /// <remarks/>
        public string cadenaQR {
            get {
                return this.cadenaQRField;
            }
            set {
                this.cadenaQRField = value;
                this.RaisePropertyChanged("cadenaQR");
            }
        }
        
        /// <remarks/>
        public string tokenDownload {
            get {
                return this.tokenDownloadField;
            }
            set {
                this.tokenDownloadField = value;
                this.RaisePropertyChanged("tokenDownload");
            }
        }
        
        /// <remarks/>
        public string urlDownloadXML {
            get {
                return this.urlDownloadXMLField;
            }
            set {
                this.urlDownloadXMLField = value;
                this.RaisePropertyChanged("urlDownloadXML");
            }
        }
        
        /// <remarks/>
        public string urlDownloadPDF {
            get {
                return this.urlDownloadPDFField;
            }
            set {
                this.urlDownloadPDFField = value;
                this.RaisePropertyChanged("urlDownloadPDF");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.facturadigital.com.mx/soap/FacturaDigitalWebService")]
    public partial class RespuestaEnviarCorreo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.facturadigital.com.mx/soap/FacturaDigitalWebService")]
    public partial class RespuestaConsultarCreditos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensajeField;
        
        private string creditosField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        public string creditos {
            get {
                return this.creditosField;
            }
            set {
                this.creditosField = value;
                this.RaisePropertyChanged("creditos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.facturadigital.com.mx/soap/FacturaDigitalWebService")]
    public partial class RespuestaCancelarCFDI : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string mensajeErrorField;
        
        /// <remarks/>
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        public string mensajeError {
            get {
                return this.mensajeErrorField;
            }
            set {
                this.mensajeErrorField = value;
                this.RaisePropertyChanged("mensajeError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarCFDIPorTexto", WrapperNamespace="https://www.facturadigital.com.mx/SecureWebService", IsWrapped=true)]
    public partial class generarCFDIPorTextoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string contrasena;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string stringTexto;
        
        public generarCFDIPorTextoRequest() {
        }
        
        public generarCFDIPorTextoRequest(string usuario, string contrasena, string stringTexto) {
            this.usuario = usuario;
            this.contrasena = contrasena;
            this.stringTexto = stringTexto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarCFDIPorTextoResponse", WrapperNamespace="https://www.facturadigital.com.mx/SecureWebService", IsWrapped=true)]
    public partial class generarCFDIPorTextoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public DisiProject.FacturaDigitalWS.RespuestaGenerarCFDIPorTexto @return;
        
        public generarCFDIPorTextoResponse() {
        }
        
        public generarCFDIPorTextoResponse(DisiProject.FacturaDigitalWS.RespuestaGenerarCFDIPorTexto @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarCFDI", WrapperNamespace="https://www.facturadigital.com.mx/SecureWebService", IsWrapped=true)]
    public partial class cancelarCFDIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string contrasena;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string uuid;
        
        public cancelarCFDIRequest() {
        }
        
        public cancelarCFDIRequest(string usuario, string contrasena, string uuid) {
            this.usuario = usuario;
            this.contrasena = contrasena;
            this.uuid = uuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarCFDIResponse", WrapperNamespace="https://www.facturadigital.com.mx/SecureWebService", IsWrapped=true)]
    public partial class cancelarCFDIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public DisiProject.FacturaDigitalWS.RespuestaCancelarCFDI @return;
        
        public cancelarCFDIResponse() {
        }
        
        public cancelarCFDIResponse(DisiProject.FacturaDigitalWS.RespuestaCancelarCFDI @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarCreditos", WrapperNamespace="https://www.facturadigital.com.mx/SecureWebService", IsWrapped=true)]
    public partial class consultarCreditosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string contrasena;
        
        public consultarCreditosRequest() {
        }
        
        public consultarCreditosRequest(string usuario, string contrasena) {
            this.usuario = usuario;
            this.contrasena = contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarCreditosResponse", WrapperNamespace="https://www.facturadigital.com.mx/SecureWebService", IsWrapped=true)]
    public partial class consultarCreditosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public DisiProject.FacturaDigitalWS.RespuestaConsultarCreditos @return;
        
        public consultarCreditosResponse() {
        }
        
        public consultarCreditosResponse(DisiProject.FacturaDigitalWS.RespuestaConsultarCreditos @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarCorreo", WrapperNamespace="https://www.facturadigital.com.mx/SecureWebService", IsWrapped=true)]
    public partial class enviarCorreoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string contrasena;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string token;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string destinatario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string mensajehtml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string templatecode;
        
        public enviarCorreoRequest() {
        }
        
        public enviarCorreoRequest(string usuario, string contrasena, string uuid, string token, string destinatario, string mensajehtml, string templatecode) {
            this.usuario = usuario;
            this.contrasena = contrasena;
            this.uuid = uuid;
            this.token = token;
            this.destinatario = destinatario;
            this.mensajehtml = mensajehtml;
            this.templatecode = templatecode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarCorreoResponse", WrapperNamespace="https://www.facturadigital.com.mx/SecureWebService", IsWrapped=true)]
    public partial class enviarCorreoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public DisiProject.FacturaDigitalWS.RespuestaEnviarCorreo @return;
        
        public enviarCorreoResponse() {
        }
        
        public enviarCorreoResponse(DisiProject.FacturaDigitalWS.RespuestaEnviarCorreo @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FacturaDigitalWebServicePortTypeChannel : DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacturaDigitalWebServicePortTypeClient : System.ServiceModel.ClientBase<DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType>, DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType {
        
        public FacturaDigitalWebServicePortTypeClient() {
        }
        
        public FacturaDigitalWebServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacturaDigitalWebServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturaDigitalWebServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacturaDigitalWebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DisiProject.FacturaDigitalWS.generarCFDIPorTextoResponse DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType.generarCFDIPorTexto(DisiProject.FacturaDigitalWS.generarCFDIPorTextoRequest request) {
            return base.Channel.generarCFDIPorTexto(request);
        }
        
        public DisiProject.FacturaDigitalWS.RespuestaGenerarCFDIPorTexto generarCFDIPorTexto(string usuario, string contrasena, string stringTexto) {
            DisiProject.FacturaDigitalWS.generarCFDIPorTextoRequest inValue = new DisiProject.FacturaDigitalWS.generarCFDIPorTextoRequest();
            inValue.usuario = usuario;
            inValue.contrasena = contrasena;
            inValue.stringTexto = stringTexto;
            DisiProject.FacturaDigitalWS.generarCFDIPorTextoResponse retVal = ((DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType)(this)).generarCFDIPorTexto(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DisiProject.FacturaDigitalWS.generarCFDIPorTextoResponse> DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType.generarCFDIPorTextoAsync(DisiProject.FacturaDigitalWS.generarCFDIPorTextoRequest request) {
            return base.Channel.generarCFDIPorTextoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DisiProject.FacturaDigitalWS.generarCFDIPorTextoResponse> generarCFDIPorTextoAsync(string usuario, string contrasena, string stringTexto) {
            DisiProject.FacturaDigitalWS.generarCFDIPorTextoRequest inValue = new DisiProject.FacturaDigitalWS.generarCFDIPorTextoRequest();
            inValue.usuario = usuario;
            inValue.contrasena = contrasena;
            inValue.stringTexto = stringTexto;
            return ((DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType)(this)).generarCFDIPorTextoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DisiProject.FacturaDigitalWS.cancelarCFDIResponse DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType.cancelarCFDI(DisiProject.FacturaDigitalWS.cancelarCFDIRequest request) {
            return base.Channel.cancelarCFDI(request);
        }
        
        public DisiProject.FacturaDigitalWS.RespuestaCancelarCFDI cancelarCFDI(string usuario, string contrasena, string uuid) {
            DisiProject.FacturaDigitalWS.cancelarCFDIRequest inValue = new DisiProject.FacturaDigitalWS.cancelarCFDIRequest();
            inValue.usuario = usuario;
            inValue.contrasena = contrasena;
            inValue.uuid = uuid;
            DisiProject.FacturaDigitalWS.cancelarCFDIResponse retVal = ((DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType)(this)).cancelarCFDI(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DisiProject.FacturaDigitalWS.cancelarCFDIResponse> DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType.cancelarCFDIAsync(DisiProject.FacturaDigitalWS.cancelarCFDIRequest request) {
            return base.Channel.cancelarCFDIAsync(request);
        }
        
        public System.Threading.Tasks.Task<DisiProject.FacturaDigitalWS.cancelarCFDIResponse> cancelarCFDIAsync(string usuario, string contrasena, string uuid) {
            DisiProject.FacturaDigitalWS.cancelarCFDIRequest inValue = new DisiProject.FacturaDigitalWS.cancelarCFDIRequest();
            inValue.usuario = usuario;
            inValue.contrasena = contrasena;
            inValue.uuid = uuid;
            return ((DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType)(this)).cancelarCFDIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DisiProject.FacturaDigitalWS.consultarCreditosResponse DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType.consultarCreditos(DisiProject.FacturaDigitalWS.consultarCreditosRequest request) {
            return base.Channel.consultarCreditos(request);
        }
        
        public DisiProject.FacturaDigitalWS.RespuestaConsultarCreditos consultarCreditos(string usuario, string contrasena) {
            DisiProject.FacturaDigitalWS.consultarCreditosRequest inValue = new DisiProject.FacturaDigitalWS.consultarCreditosRequest();
            inValue.usuario = usuario;
            inValue.contrasena = contrasena;
            DisiProject.FacturaDigitalWS.consultarCreditosResponse retVal = ((DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType)(this)).consultarCreditos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DisiProject.FacturaDigitalWS.consultarCreditosResponse> DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType.consultarCreditosAsync(DisiProject.FacturaDigitalWS.consultarCreditosRequest request) {
            return base.Channel.consultarCreditosAsync(request);
        }
        
        public System.Threading.Tasks.Task<DisiProject.FacturaDigitalWS.consultarCreditosResponse> consultarCreditosAsync(string usuario, string contrasena) {
            DisiProject.FacturaDigitalWS.consultarCreditosRequest inValue = new DisiProject.FacturaDigitalWS.consultarCreditosRequest();
            inValue.usuario = usuario;
            inValue.contrasena = contrasena;
            return ((DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType)(this)).consultarCreditosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DisiProject.FacturaDigitalWS.enviarCorreoResponse DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType.enviarCorreo(DisiProject.FacturaDigitalWS.enviarCorreoRequest request) {
            return base.Channel.enviarCorreo(request);
        }
        
        public DisiProject.FacturaDigitalWS.RespuestaEnviarCorreo enviarCorreo(string usuario, string contrasena, string uuid, string token, string destinatario, string mensajehtml, string templatecode) {
            DisiProject.FacturaDigitalWS.enviarCorreoRequest inValue = new DisiProject.FacturaDigitalWS.enviarCorreoRequest();
            inValue.usuario = usuario;
            inValue.contrasena = contrasena;
            inValue.uuid = uuid;
            inValue.token = token;
            inValue.destinatario = destinatario;
            inValue.mensajehtml = mensajehtml;
            inValue.templatecode = templatecode;
            DisiProject.FacturaDigitalWS.enviarCorreoResponse retVal = ((DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType)(this)).enviarCorreo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DisiProject.FacturaDigitalWS.enviarCorreoResponse> DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType.enviarCorreoAsync(DisiProject.FacturaDigitalWS.enviarCorreoRequest request) {
            return base.Channel.enviarCorreoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DisiProject.FacturaDigitalWS.enviarCorreoResponse> enviarCorreoAsync(string usuario, string contrasena, string uuid, string token, string destinatario, string mensajehtml, string templatecode) {
            DisiProject.FacturaDigitalWS.enviarCorreoRequest inValue = new DisiProject.FacturaDigitalWS.enviarCorreoRequest();
            inValue.usuario = usuario;
            inValue.contrasena = contrasena;
            inValue.uuid = uuid;
            inValue.token = token;
            inValue.destinatario = destinatario;
            inValue.mensajehtml = mensajehtml;
            inValue.templatecode = templatecode;
            return ((DisiProject.FacturaDigitalWS.FacturaDigitalWebServicePortType)(this)).enviarCorreoAsync(inValue);
        }
    }
}
